name: flutter_app
description: Atık Tespit Uygulaması
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: 0.10.5+9
  image_picker: ^1.2.1
  tflite_flutter: ^0.12.1
  http: ^1.2.0
  image: ^4.7.2
  # tflite_flutter_helper kaldırıldı

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/labels.txt